# Generated by Django 3.2.6 on 2021-09-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='uplaod_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
