# Generated by Django 4.0.5 on 2022-06-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reporter',
            new_name='publisher',
        ),
    ]
