# Generated by Django 3.2.6 on 2021-09-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='joindate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
